export { calciumGenerator } from "./generator"

import "./assign"
import "./variable"
import "./binOp"
import "./num"
import "./string"
import "./array"
import "./if"
import "./forOf"
import "./p"
import "./text"
import "./css"
import "./on"
